apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: node-pool
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  resources:
    requests:
      memory: 512M
      cpu: 1
    limits:
      memory: 4G
      cpu: 4
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 5Gi
    deleteClaim: true
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    #authorization:
    #  type: simple
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      # - name: external
      #   port: 9095
      #   type: ingress
      #   tls: true
      #   authentication:
      #     type: tls
      #   configuration:
      #     class: public
      #     bootstrap:
      #       host: kafka-bootstrap.local
      #     hostTemplate: broker-{nodeId}.local 
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.9"
      auto.create.topics.enable: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi