apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: imdg
  namespace: coherence
spec:
  replicas: 3
  cluster: imdg
  role: Storage
  image: ttl.sh/dc96a2da-42ce-455d-8827-f9256c16f81f:10m
  imagePullPolicy: Always
  application:
    main: com.egt.digital.platform.services.coherence.CoherenceClusterNodeApplication
  #configMapVolumes:
  #  - name: coherence-config
  #    mountPath: /config
  jvm:
    args:
      - "-XX:-UseG1GC"
      - "-XX:+UseZGC"
      - "-XX:ZUncommitDelay=30"
      - "-XX:+ZGenerational"
      - "-Djava.net.preferIPv4Stack=true"
      - "--add-opens java.base/java.io=ALL-UNNAMED"
      - "--add-opens java.base/java.lang=ALL-UNNAMED"
      - "-Dserver.port=8888"
      - "-Dspring.profiles.active=kubernetes"
    memory:
      initialRAMPercentage: 10
      minRAMPercentage: 5
      maxRAMPercentage: 80
  coherence:
    #cacheConfig: /config/coherence-cache-config.xml
    #overrideConfig: /config/tangosol-coherence-override.xml
    storageEnabled: true
    management:
      enabled: true
    logLevel: 9
    persistence:
      mode: active
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      snapshots:
        persistentVolumeClaim:
          accessModes:
            - ReadWriteOnce
          resources:  
            requests:
              storage: 5Gi
    metrics:
      enabled: true 
  env:
    - name: "COHERENCE_METRICS_LEGACY_NAMES"
      value: "false"
  ports:
    - name: management
      port: 30000
    - name: extend-http
      port: 8080
    - name: extend-tcp
      port: 9090
    - name: extend-proxy
      port: 9091  
    - name: metrics
      serviceMonitor:
        enabled: true
    - name: spring-web
      port: 8888
    - name: spring-actuator
      port: 8090

  initResources:           
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  resources:
      requests:
        memory: "8G"
        #cpu: "4"
      limits:
        memory: "16G"
        #cpu: "8"

