apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imdg-extend-http
  namespace: coherence
spec:
  rules:
  - host: imdg-rest.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: imdg-extend-http
            port:
              name: extend-http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imdg-management
  namespace: coherence
spec:
  rules:
  - host: imdg-management.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: imdg-management
            port:
              name: management
---
