- name: Install Cert Manager
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Create Cert Manager namespace
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: cert-manager
            labels:
              metrics: enabled

    - name: Add Cert Manager helm repository
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"
        force_update: true

    - name: Install Cert Manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        chart_version: 1.16.3
        values_files:
          - resources/cert-manager/values.yml