- name: Install Coherence
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Create Coherence namespace
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: coherence
            labels:
              metrics: enabled

    - name: Add Coherence helm repository
      kubernetes.core.helm_repository:
        name: coherence
        repo_url: "https://oracle.github.io/coherence-operator/charts"
        force_update: true

    - name: Install Coherence Cluster operator
      kubernetes.core.helm:
        name: coherence
        chart_ref: coherence/coherence-operator
        release_namespace: coherence
        values_files:
         - resources/coherence/values.yml

