- name: Install Elasticsearch Exporter
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Add Elasticsearch Exporter helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Install Elasticsearch Exporter
      kubernetes.core.helm:
        name: prometheus-elasticsearch-exporter
        chart_ref: prometheus-community/prometheus-elasticsearch-exporter
        release_namespace: elasticsearch 
        values_files:
          - resources/elasticsearch-exporter/values.yml

    - name: Get Grafana admin user
      kubernetes.core.k8s_info:
        kind: Secret
        name: kube-prometheus-stack-grafana
        namespace: monitoring
      register: grafana

    - name: Find all Elasticsearch dashboards
      ansible.builtin.find:
        paths: resources/elasticsearch-exporter/grafana
      register: files

    - name: Create Elasticsearch Grafana folder
      community.grafana.grafana_folder:
        url: http://grafana.local
        grafana_user: "{{ grafana.resources[0].data['admin-user'] |  b64decode }}"
        grafana_password: "{{ grafana.resources[0].data['admin-password'] | b64decode }}"
        title: "Elasticsearch"
        state: present

    - name: Import Elasticsearch Grafana dashboards
      community.grafana.grafana_dashboard:
        grafana_url: http://grafana.local
        grafana_user: "{{ grafana.resources[0].data['admin-user'] |  b64decode }}"
        grafana_password: "{{ grafana.resources[0].data['admin-password'] | b64decode }}"
        folder: "Elasticsearch"
        state: present
        overwrite: false
        path: "{{item}}"
      with_items: "{{ files.files |  map(attribute='path') }}"
      ignore_errors: true