- name: Install Kafka UI
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    
    - name: Add Kafka UI helm repository
      kubernetes.core.helm_repository:
        name: kafka-ui
        repo_url: "https://provectus.github.io/kafka-ui-charts"
    
    - name: Install Kafka UI
      kubernetes.core.helm:
        name: kafka-ui
        chart_ref: kafka-ui/kafka-ui
        release_namespace: kafka
        chart_version: 0.7.6
        values_files:
          - resources/kafka-ui/values.yaml

