- name: Provision Kubernetes Prometheus stack
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Add Prometheus helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"
    - name: Install Prometheus and Grafana
      kubernetes.core.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        chart_version: 68.2.1
        create_namespace: true
        values_files:
          - resources/kube-prom-stack/values.yaml