- name: Provision Longhorn block storage
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:  
    - name: Add Longhorn helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"
    - name: Install Longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        chart_version: 1.7.2
        create_namespace: true
        values_files:
          - resources/longhorn/values.yaml
      register: result

    - name: Change local-path StorageClass not to be deault
      kubernetes.core.k8s:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: local-path
        state: patched
        definition:
          metadata:
            annotations:
              "storageclass.kubernetes.io/is-default-class" : "false"